---
title: "Model Fitting and Results"
author: "He et al."
date: "`r Sys.Date()`"
output: 
  bookdown::html_document2:
    toc: true
    toc_float: true
    toc_depth: 2
---

```{r setup, include=FALSE}
library(tidyverse) # for data wrangling
library(mosaic) # for ggformula graphics
library(plotly) # for interactive graphs
# library(readxl) # read excel files
# library(evomap) # for PGLS ancova/CI/PIs
# library(ape) # for trees
# library(mice) # for pooling estimated from fitted pgls models
# library(broom.mixed) # for pulling results out of gls fitted model objects
# library(carEx) # for ANOVA for pgls
# to install carEx:
# install.packages("carEx", repos="http://R-Forge.R-project.org")
# to install evomap run:
# remotes::install_github('JeroenSmaers/evomap')
# library(MuMIn) # don't think we are using (for dredge, AIC/BIC comparisons)
library(lme4)
library(car)  #  needed for Anova(), avPlots, vif functions
library(MuMIn)  #  needed for dredge function, pgls utilities?
library(sjPlot) # for tables of model summary info
library(pander) # for table of Anova() results
# library(nlme) # for gls()
# library(multcomp)
# library(nlstools)
library(ggeffects) # for plotting marginal model predictions
library(glmmTMB) # for fitting RE models. 
library(janitor) # to easily remove empty rows
# source("utils/augPairs.R")  #  needed for aug.pairs function
# source("utils/MuMInUtilities.R")  #  needed for MuMIn.shrink.fit and MuMIn.shrink.resid
# source("utils/qqnormWithBounds.R") 
# source("PGLS model/broom_gls.R")
knitr::opts_chunk$set(echo = TRUE, message = FALSE, 
                      warning = FALSE, cache = TRUE,
                      fig.path = 'figures/',
                      fig.cap = "&nbsp;")
theme_set(theme_minimal(base_size = 14))
my_colors <- RColorBrewer::brewer.pal(3, "Paired")[2:3]
# below were for PGLS
# source('utils/gls-utils.R')
# source('utils/Anova.mira.R')
```

```{r, child = 'bmr-2022.Rmd'}
```

```{r, child = 'filtered-fr-2022.Rmd'}
```

```{r, child = 'filtered-hr-2022.Rmd'}
```

```{r, child = 'filtered-sv-2022.Rmd'}
```

```{r, child = 'filtered-vt-2022.Rmd'}
```

```{r, child = 'filter-more-predictions.Rmd'}
```


```{r, child = 'filter-more-comparisons-22.Rmd'}
```