---
title: "Supplemental Materials"
author: "He et al."
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
---

```{r setup, include=FALSE}
require(tidyverse) # for data wrangling
require(mosaic) # for ggformula graphics
require(plotly) # for interactive graphs
# require(evomap) # for PGLS ancova/CI/PIs
require(ape) # for trees
require(mice) # for pooling estimated from fitted pgls models
require(broom.mixed) # for pulling results out of gls fitted model objects
require(carEx) # for ANOVA for pgls
# to install carEx:
# install.packages("carEx", repos="http://R-Forge.R-project.org")
# to install evomap run:
# remotes::install_github('JeroenSmaers/evomap')
# require(MuMIn) # don't think we are using (for dredge, AIC/BIC comparisons)
require(car)  #  needed for Anova(), avPlots, vif functions
require(MuMIn)  #  needed for dredge function, pgls utilities?
require(sjPlot) # for tables of model summary info
require(pander) # for table of Anova() results
require(nlme) # for gls()
# require(multcomp)
# require(nlstools)
require(ggeffects) # for plotting marginal model predictions
require(glmmTMB) # for fitting RE models. can use lme4 also
# source("utils/augPairs.R")  #  needed for aug.pairs function
# source("utils/MuMInUtilities.R")  #  needed for MuMIn.shrink.fit and MuMIn.shrink.resid
# source("utils/qqnormWithBounds.R") 
# source("PGLS model/broom_gls.R")
knitr::opts_chunk$set(echo = TRUE, message = FALSE, 
                      warning = FALSE, cache = TRUE,
                      fig.path = 'figures/')
theme_set(theme_minimal(base_size = 14))
my_colors <- RColorBrewer::brewer.pal(3, "Paired")[2:3]

source('utils/gls-utils.R')
source('utils/Anova.mira.R')
```

```{r, child = 'all-models-bmr.Rmd'}
```

```{r, child = 'all-models-fr.Rmd'}
```

```{r, child = 'all-models-hr.Rmd'}
```

```{r, child = 'all-models-sv.Rmd'}
```

```{r, child = 'all-models-vt.Rmd'}
```

```{r, child = 'more-predictions.Rmd'}
```